apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.kialigateway }}
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15032
      name: http-kiali
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio.kialivs }}
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio.kialigateway }}
  http:
  - match:
    - port: 15032
    route:
    - destination:
        host: kiali
        port:
          number: 20001
